<a href="https://colab.research.google.com/github/harrisb002/CS_479/blob/Labs/jupyter_notebook_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### CS479 Python Tutorial With Jupyter Notebook

This tutorial was originally written by [Justin Johnson](https://web.eecs.umich.edu/~justincj/) for Stanford's [cs231n](http://cs231n.stanford.edu/) and adapted as a Jupyter notebook for cs228 by [Volodymyr Kuleshov](http://web.stanford.edu/~kuleshov/) and [Isaac Caswell](https://symsys.stanford.edu/viewing/symsysaffiliate/21335), and later by Kevin Zakka for the Spring 2020 edition of [cs231n](http://cs231n.stanford.edu/).

This current version has been further adapted for the Fall 2023 CS 479 course at Sonoma State University.

## What is a Jupyter Notebook?

A Jupyter notebook is made up of a number of cells. Each cell can contain Python code. There are two main types of cells: `Code` cells and `Markdown` cells. This particular cell is a `Markdown` cell. You can execute a particular cell by clicking on it (the highlight color will switch from blue to green) and pressing `Shift-Enter`. When you do so, if the cell is a `Code` cell, the code in the cell will run, and the output of the cell will be displayed beneath the cell, and if the cell is a `Markdown` cell, the markdown text will get rendered beneath the cell.

Go ahead and try executing this cell.

The cell below is a `Code` cell. Go ahead and click it, then execute it.

In [ ]:
x = 1
print(x)

1


Global variables are shared between cells. Try executing the cell below:

In [ ]:
y = 2 * x
print(y)

2


### Keyboard Shortcuts

There are a few keyboard shortcuts you should be aware of to make your notebook experience more pleasant. To escape editing of a cell, press `esc`. Escaping a `Markdown` cell won't render it, so make sure to execute it if you wish to render the markdown. Notice how the highlight color switches back to blue when you have escaped a cell.

You can navigate between cells by pressing your arrow keys. Executing a cell automatically shifts the cell cursor down 1 cell if one exists, or creates a new cell below the current one if none exist.

* To insert a cell below the current one, press `b`.
* To insert a cell above the current one, press `a`.
* To delete a cell, press `dd`.
* To convert a cell to `Markdown` press `m`. Note you have to be in `esc` mode.
* To convert it back to `Code` press `y`. Note you have to be in `esc` mode.

Get familiar with these keyboard shortcuts, they really help!

You can restart a notebook and clear all cells by clicking `Kernel -> Restart & Clear Output`. If you don't want to clear cell outputs, just hit `Kernel -> Restart`.

By convention, Jupyter notebooks are expected to be run from top to bottom. Failing to execute some cells or executing cells out of order can result in errors. After restarting the notebook, try running the `y = 2 * x` cell 2 cells above and observe what happens.

After you have modified a Jupyter notebook for one of the assignments by modifying or executing some of its cells, remember to save your changes! You can save with the `Command/Control + s` shortcut or by clicking `File -> Save and Checkpoint`.

This has only been a brief introduction to Jupyter notebooks, but it should be enough to get you up and running on the labs and assignments for this course.

## Python Tutorial

Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (numpy, scipy, matplotlib) it becomes a powerful environment for scientific computing.

We expect that many of you will have some experience with Python and numpy; for the rest of you, this section will serve as a quick crash course both on the Python programming language and on the use of Python for scientific computing.

Some of you may have previous knowledge in Matlab, in which case we also recommend the numpy for Matlab users page (https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html).

In this lab, we will cover:

* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes
* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting
* IPython: Creating notebooks, Typical workflows

Along the way, you will be given **short code snippets to write**. These will assess the understanding of the basics covered above. At the end of the lab, instructions will be provided on how to submit the notebook for grading.

## A Brief Note on Python Versions

As of Janurary 1, 2020, Python has [officially dropped support](https://www.python.org/doc/sunset-python-2/) for `python2`. **We'll be using Python 3.10 for this iteration of the course.**

You should have activated your `tflabsf23` conda environment created in the [Setup Instructions](https://canvas.sonoma.edu/courses/37563/pages/starting-labs-and-assignments) before calling `jupyter notebook`. If that is
the case, the cell below should print out a major version of 3.10.

In [ ]:
!python --version

Python 3.10.12


## Basics of Python

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable. As an example, here is an implementation of the classic quicksort algorithm in Python:

In [ ]:
#function definition
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]

    #Quick way to partition arr
    left = [x for x in arr if x < pivot] #all values less than pivot
    middle = [x for x in arr if x == pivot] #all values equal to pivot
    right = [x for x in arr if x > pivot] #all values greater than pivot

    return quicksort(left) + middle + quicksort(right)

In [ ]:
#function invocation
print(quicksort([3,6,8,10,1,2,1]))
print(quicksort([30,6,83,10,14,2,19]))

[1, 1, 2, 3, 6, 8, 10]
[2, 6, 10, 14, 19, 30, 83]


### Basic data types

#### Numbers

Integers and floats work as you would expect from other languages:

In [ ]:
x = 3
print(x, type(x))

3 <class 'int'>


In [ ]:
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x ** 2)  # Exponentiation

4
2
6
9


In [ ]:
x += 1
print(x)
x *= 2
print(x)

4
8


In [ ]:
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)

<class 'float'>
2.5 3.5 5.0 6.25


Note that unlike many languages, Python does not have unary increment (x++) or decrement (x--) operators.

Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3.9/library/stdtypes.html#numeric-types-int-float-long-complex).

#### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):

In [ ]:
t, f = True, False
print(type(t))

<class 'bool'>


Now we let's look at the operations:

In [ ]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

False
True
False
True


#### Strings

In [ ]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter
print(hello, len(hello))

hello 5


In [ ]:
hw = hello + ' ' + world  # String concatenation
print(hw)

hello world


In [ ]:
#Use {} to indicate placeholders for variables/constants
hw12 = '{} {} {}'.format(hello, world, 12)  # string formatting
print(hw12)

#alternative
val  = 24
hw25 = 'hello world {}'.format(val+1)  # string formatting
print(hw25)

hello world 12
hello world 25


String objects have a bunch of useful methods; for example:

In [ ]:
s = "hello"
print(s.capitalize())  # Capitalize a string
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces
print(s.center(7))     # Center a string, padding with spaces
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another
print('  world '.strip())  # Strip leading and trailing whitespace

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


You can find a list of all string methods in the [documentation](https://docs.python.org/3.9/library/stdtypes.html#string-methods).

### Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples.

#### Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [ ]:
xs = [3, 1, 2]   # Create a list
print(xs, xs[2])
print(xs[-1])     # Negative indices count from the end of the list; prints "2"

[3, 1, 2] 2
2


In [ ]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

[3, 1, 'foo']


In [ ]:
xs.append('bar') # Add a new element to the end of the list
print(xs)

[3, 1, 'foo', 'bar']


In [ ]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs)

bar [3, 1, 'foo']


As usual, you can find all the gory details about lists in the [documentation](https://docs.python.org/3.9/tutorial/datastructures.html#more-on-lists).

#### Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [ ]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


#### Loops

You can loop over the elements of a list like this:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

#1: cat
#2: dog
#3: monkey


#### List comprehensions

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


You can make this code simpler using a list comprehension:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


List comprehensions can also contain conditions:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


#### Dictionaries

A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

cute
True


In [ ]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"

wet


In [ ]:
d['fish'] = 'scale'    # Update an entry in a dictionary
print(d['fish'])      # Prints "scale"

scale


In [ ]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

In [ ]:
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "scale"

N/A
scale


In [ ]:
del d['fish']        # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

In [ ]:
e = {} #start from an empty dictonary
key = 12 #some integer
value = 'important' #some string
e[key] = value
print(e)

You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/3.9/library/stdtypes.html#dict).

It is easy to iterate over the keys in a dictionary:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A {} has {} legs'.format(animal, legs))

Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_squares = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_squares)

{0: 0, 2: 4, 4: 16}


#### Sets

A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"


In [ ]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # Number of elements in a set;

In [ ]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(len(animals))
animals.remove('cat')    # Remove an element from a set
print(len(animals))

*Loops*: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

Set comprehensions: Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [ ]:
from math import sqrt
print({int(sqrt(x)) for x in range(30)})

#### Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print(type(t))
print(d[t])
print(d[(1, 2)])
print(d)
print (d[2,3])

In [ ]:
t[0] = 1 #TypeError. tuples are immutable (i.e. can't be changed).

### Functions

Python functions are defined using the `def` keyword. For example:

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

Here is your first piece of code that you need to write yourself and that will be graded.
Do NOT edit anything other than the location indicated (below where it says `# YOUR CODE HERE`)
When you are done with your code, remove the line `raise NotImplementedError()`.

Your code is automatically tested through calls to `assert` function. The cells containing the `assert` function calls are uneditable. The `assert` function raises an error if the condition it is evaluating is `False`. You should use that as feedback to correct your code.


## Part A (4 points)

Write a function that returns `True` if an input number is even, `False` otherwise.

In [ ]:
def isEven(num):
    """Returns True if num is even, False otherwise
    """
    # YOUR CODE HERE
    if num % 2 == 0:
      return True
    else:
      return False

Your function should return `True` for $num=10$ and `False` for $num = 101$. Check that it does:

In [ ]:
isEven(10)

True

In [ ]:
isEven(101)

False

In [ ]:
"""Check that isEven returns the correct output for several inputs"""
assert isEven(1) == False
assert isEven(2) == True
assert isEven(10324135) == False
assert isEven(-452114) == True

We can define functions to take optional keyword arguments, like this:

In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))

hello('Bob')
hello('Fred', loud=True)

### Classes

The syntax for defining classes in Python is straightforward:

In [ ]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
          print('HELLO, {}'.format(self.name.upper()))
        else:
          print('Hello, {}!'.format(self.name))

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools/operations for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html) useful to get started with Numpy.

To use Numpy, we first need to import the `numpy` package:

In [ ]:
import numpy as np

### Numpy Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [ ]:
a = np.array([1,2,3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print (a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr.shape)

(2, 3)


In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b, b.ndim, b.shape)

[[1 2 3]
 [4 5 6]] 2 (2, 3)


In [ ]:
print('Rank is', b.ndim) #number of dimensions (rank)
print('Shape is', b.shape) #size along each dimension
print('Type of shape is', type(b.shape)) #size along each dimension
print(b[0, 0], b[0, 1], b[1, 0])


Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,3))  # Create an array of all zeros. Argument is the shape of the desired array.
print(a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

## Part B (1 point)
Create a numpy array m with 3 rows and 4 columns and containing random values

In [ ]:
# YOUR CODE HERE
m = np.random.random((3,4))

In [ ]:
#Ensure that the shape of this array is (3, 4)
assert m.shape == (3, 4)

Using [arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html?highlight=arange#numpy.arange) to generate range of values (this is similar to the built-in range() function)

In [ ]:
#Use arange function to generate an np array from a range
f1 = np.arange(12)
print(f1) #One-dimensional arrays are printed as rows

#Use reshape method to convert into a 2D array
f = f1.reshape(4, 3)  # 2d array
print(f) #Two-dimensional arrays are printed as matrices


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
#Combine both arange and reshape in one line
g = np.arange(24).reshape(2, 3, 4)  # 3d array
print(g) #Three-dimensional arrays are printed as lists of matrices

### Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)
b.shape

A slice of an array is a [view](https://numpy.org/doc/stable/glossary.html#term-view) into the same data, so **modifying it will modify the original array**.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an subarray of the same rank as the
original array:

In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a (using integer indexing)
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a (using slices)

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [ ]:
#When fewer indices are provided than the number of axes (dimensions), the missing indices are considered complete slices:
row_r1a = a[1]      # Same as a[1, :] (row_r1 above). The expression within brackets in a[i] is treated as an i followed by
                    # as many instances of : as needed to represent the remaining axes.
print(row_r1a, row_r1a.shape)

[5 6 7 8] (4,)


In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1] # (using integer indexing)
col_r2 = a[:, 1:2] # (using slices)

print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


## Part C (4 points)
 - create a numpy array `m` with 5 rows and 3 columns that has values uniformly between 10 and 24 (using `arange` function)
 - next, create numpy array `m1` that stores the second column of `m` only. shape of `m1` must be (5, 1)
 - next, create numpy array `m2` that stores the last two rows of `m`. shape of `m2` must be (2, 3)

In [ ]:
# YOUR CODE HERE
m = np.arange(26)
m = m[10:25]
m = m.reshape(5,3)

# indexing method requires reshaping to (5,1) becuase it is currently (5,)
# m1 = m[:, 1]
# m1.reshape(5,1)
# However by using slicing you can bypass this
m1 = m[:, 1:2]

# Slices row 3 & onward & all columns
m2 = m[3:, :]

print(m)
print()
print(m1)
print()
print(m2)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]

[[11]
 [14]
 [17]
 [20]
 [23]]

[[19 20 21]
 [22 23 24]]


In [ ]:
#test that m, m1, and m2 are correctly built
assert m1.shape == (5, 1)
assert m2.shape == (2, 3)
assert np.array_equal(m1, np.array([[11], [14], [17], [20], [23]]))
assert np.array_equal(m2, np.array([[19,20,21], [22,23,24]]))

## Integer array indexing
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print (a)
print()

# An example of integer array indexing.
# The returned array will have shape (2,)
print(a[[1, 2], [0, 1]])
print()

# The above example of integer array indexing is equivalent to this:
print(np.array([a[1,0], a[2,1]]))
print()

# An example of integer array indexing.
# The returned array will have shape (3,)
print(a[[0, 1, 2], [0, 1, 0]])
print()

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[[1 2]
 [3 4]
 [5 6]]

[3 6]

[3 6]

[1 4 5]

[1 4 5]


In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)
print()

c = np.array([1,1,1,1])
a[np.arange(4),c] +=20
print(a)

[[51  2  3]
 [ 4  5 56]
 [57  8  9]
 [10 61 12]]

[[51 22  3]
 [ 4 25 56]
 [57 28  9]
 [10 81 12]]


## Part D (2 points)

Mutate the diagonal elements of an array a
 - Diagonal elements are at indices `[0, 0]`, `[1, 1]`, `[2, 2]`, and so on..
 - Code for generating and mutating the array a is already provided
 - Your code only needs to generate the array of indices `i` corresponding to the diagonal elements


In [ ]:
#Generate array
a = np.arange(16).reshape(4, 4)

#Create a numpy array of indices i that will enable mutation of the diagonal elements of a
# YOUR CODE HERE
i = np.array([0,1,2,3])

#Mutate array
a[i, i] += 50 #add 50 to the diagonal elements of a
print(a)

[[50  1  2  3]
 [ 4 55  6  7]
 [ 8  9 60 11]
 [12 13 14 65]]


In [ ]:
assert i.shape == (4,)
assert np.array_equal(a[i, i], np.array([50, 55, 60, 65]))

## Boolean array indexing
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
print()

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.
print(a.shape, bool_idx.shape)
print()
print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]

(3, 2) (3, 2)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

b = a[a>=4]
print()
print(b)
print()

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]

[4 5 6]

[3 4 5 6]


We can also convert the boolean indices into the corresponding integer indices

In [ ]:
print("Boolean array -->")
print(bool_idx)

int_idx = np.nonzero(bool_idx) #find indices where the bool_idx is not zero (is not False)
print("\nCorresponding Integer array --> (Note: these are the indices where bool_idx is True)")
print(int_idx)

print("\nint_idx is a tuple of numpy arrays of length a.ndim")
print(type(int_idx), len(int_idx), a.ndim, type(int_idx[0]))

Boolean array -->
[[False False]
 [ True  True]
 [ True  True]]

Corresponding Integer array --> (Note: these are the indices where bool_idx is True)
(array([1, 1, 2, 2]), array([0, 1, 0, 1]))

int_idx is a tuple of numpy arrays of length a.ndim
<class 'tuple'> 2 2 <class 'numpy.ndarray'>


Just like using the boolean array indexing to find "True" elements of a, we can use the integer indices:

In [ ]:
arr = np.array([[2,4,6], [1,3,5], [8,12,16]])

# even_nums = arr[arr%2==0] #Find even numbers in arr thru bool indexing
# print(arr[even_nums])

# Or just boolean index within statement
print(arr[arr%2==0])

[ 2  4  6  8 12 16]


In [ ]:
print(a[int_idx])

[3 4 5 6]


### Can you repeat boolean indexing for an example numpy array with 3 dimensions? TRY IT!!


In [ ]:
x = np.arange(45).reshape(3,5,3)
print(x, x.shape, x.ndim)

bool_idx = np.array(x>14)

print()
print(x[bool_idx])

#Get the values in the range x>14 and x<30 and print as a 2d Arr W/out reshape
y = x[1,:]
print()
print(y, y.shape)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]] (3, 5, 3) 3

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44]

[[15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]] (5, 3)


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the [documentation](https://numpy.org/doc/stable/user/basics.indexing.html#boolean-array-indexing).

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int32)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int32


Unlike Python lists, NumPy is constrained to arrays that all contain the **same type**. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

Basic mathematical functions operate **elementwise** on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [ ]:
print(v @ w)

219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing comput
ations on arrays; one of the most useful is [`sum`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html#numpy.sum). It works by computing sum of all elements in the array, or along a particular axis, or a set of axis. Understanding sum *along an axis* can be tricky at first. Check this [blog](https://www.sharpsightlabs.com/blog/numpy-axes-explained/) to get more insight.


In [ ]:
x = np.array([[1,2],[3,4]])
print(x)
print()

print(np.sum(x))  # Compute sum of all elements; prints "10"
#Compute sum along a particular axis
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[[1 2]
 [3 4]]

10
[4 6]
[3 7]


## Part E (6 points)

Apply your understanding of boolean indexing and the function `np.sum` to find out rows of an array `a` whose sum is less than a threshold `thresh` (some number).

In [ ]:
#Note: Check out the example in the the cell below this one. It shows expected output of this function.

def findRowsWithSumLessThan(a, thresh):
    """Finds and returns those rows of the array whose sum are less than thresh.
        Do not use loops. Simply apply comparison operator on the output of sum and then use boolean indexing.
        DEMO this function to the instructor to ensure you are doing it correctly (and not simply passing tests!)
    """
    # YOUR CODE HERE
    #Find sum of rows and put array of sums into sum array
    sum = np.sum(a, axis=1)

    # print(sum)
    # print()

    #Find the row sums that are less than thresh (Array of bool values)
    # sum_less_than_thresh = np.array(sum < thresh)

    # print(a[sum_less_than_thresh])
    # print()

    #Could return a[sum_less_than_thresh] or this shorthand
    return a[np.array(sum < thresh)]

In [ ]:
#Example of using findRowsWithSumLessThan
# Construct the following array
#     array([[0, 1],
#           [2, 3],
#           [4, 5]])
y = np.arange(6).reshape(3,2) # if we sum the elements of each of row array y, we get [1, 5, 9], right??

z1 = findRowsWithSumLessThan(y, 1)  #should be empty since no row has sum < 1
z2 = findRowsWithSumLessThan(y, 10) #should be the entire array since all rows have sum < 10
z3 = findRowsWithSumLessThan(y, 5)  #should only have first row of y

print(z1, z2, z3, sep = '\n\n')

[]

[[0 1]
 [2 3]
 [4 5]]

[[0 1]]


In [ ]:
np.random.seed(0)  # seed for reproducibility

x = np.random.randint(50, size=24)
y = x.reshape(4, 6)
z = findRowsWithSumLessThan(y, 200)
#number of columns should not change
assert z.shape[1] == y.shape[1]

y = x.reshape(8, 3)
z = findRowsWithSumLessThan(y, 50)
assert z.shape[1] == y.shape[1]
assert np.array_equal(z, np.array([[3, 3, 39], [9, 19, 21]]))

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n", x.T)

[44 47  0  3  3 39  9 19 21 36 23  6 24 24 12  1 38 39 23 46 24 17 37 25]
transpose
 [44 47  0  3  3 39  9 19 21 36 23  6 24 24 12  1 38 39 23 46 24 17 37 25]


In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent
to forming a matrix `vvvv` by stacking multiple copies of `v` **vertically**, then performing elementwise summation of `x` and `vvvv`. We could implement this approach like this:

In [ ]:
vstack = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vstack)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
y = x + vstack  # Add x and vstack elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, **prepend** the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](https://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)
#print(v.reshape((3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
from numpy import newaxis

#Alternatively, instead of reshaping v, a newaxis can be added to v to make its shape (3, 1)
v1 = v[:,newaxis]
print(v1 * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])

# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
print(x, w)
print()
print(x.T)


print((x.T + w).T)

[[1 2 3]
 [4 5 6]] [4 5]

[[1 4]
 [2 5]
 [3 6]]
[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
#Yet another solution is to add a newaxis to w making it shape (2, 1) and then add it directly to x (with shape (2, 3))
new_w = w[:, newaxis]
print(new_w)
print()
print("Shape of new_w is: ", new_w.shape)
print(x + w[:, newaxis])

[[4]
 [5]]

Shape of new_w is:  (2, 1)
[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


## Part F (3 points)

Broadcasting rules permit adding a column vector (an array of shape `(4, 1)`) with a row vector (an array of shape `(1, 3)`) to produce an array of shape `(4, 3)`.

Given two one-dimensional vectors `x` and `y` with shapes `(4,)` and `(3,)`, respectively, construct a column vector from `x`, and a row vector from `y`, and add them.


In [ ]:
import numpy as np
from numpy import newaxis

x = np.array([1,2,3,4])
y = np.array([4,5,6])

x = x[:,newaxis]
y = y[newaxis,:]
sum = (x+y)

print(x)
print()
print(y)
print()
print(sum)
print()

print(x.shape, y.shape, sum.shape)

[[1]
 [2]
 [3]
 [4]]

[[4 5 6]]

[[ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]

(4, 1) (1, 3) (4, 3)


In [ ]:

def addVectors(x, y):
    '''
    Given two one-dimensional vectors x and y, this function
    converts x into a column vector and y into a row vector and returns their sum
    '''
    # YOUR CODE HERE

    # Make the current (4,) into a two dim array (4,1)
    x = x[:,newaxis]

    # Make the current (3,) into a two dim array (1,3)
    y = y[newaxis,:]

    # Therefore broadcasting is available and reults in a shape
    return (x+y)


In [ ]:
np.random.seed(0)  # seed for reproducibility

x = np.random.randint(12, size=4)
y = np.random.randint(20, size=3)
z = addVectors(x, y)
assert z.shape == (4, 3)


x = np.random.randint(12, size=2)
y = np.random.randint(20, size=3)
z = addVectors(x, y)
assert z.shape == (2, 3)
assert np.array_equal(z, np.array([[21, 7, 9], [23, 9, 11]]))

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.